### Data encoding

1. Nominal/OHE Encoding
2. label and ordinal Encoding
3. Target guided ordinal Encoding

### Nominal OHE Encoding

one hot encoding also know as nominal encoding is a technique used to represent categorical data as numerical data which is more suitable for machine learning algorithms in this technique each category is represented as a binary vector where each bit corresponds to a unique category.For example,if we have a categorical variable "color" with three possible values(red,green,blue) we can represent one hot encoding as follows


1. Red:[1,0,0]
2. Green:[0,1,0]
3. Blue:[0,0,1]


Sparse matrix : u should not use ohe when u have many many categories

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [3]:
#create a simple dataframe

df=pd.DataFrame({
    'color':['red','blue','green','red','blue']
})

In [4]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [5]:
#create isntance of one hot encoding
encoder =OneHotEncoder()

In [8]:
#perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [7]:
#why in the output red went 0,0,1 as the function did alphabetical shorting 
#it led to red to hold the last spot and blue to hold the first

In [9]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [12]:
encoder.transform([['blue']]).toarray()

/home/dazai/Yash/Data_sci/Practice /.conda/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [13]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

### label encoding

label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data 

label encoding involves assigning  a unique numerical label to each category in the variable .the label are usually assigned in alphabetical order or based on the frequency of the categories. for example if we have a categorical variable 'color' with three possible values


1. Red:1
2. Green:2
3. Blue:3

In [16]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [17]:
lbl_encoder.fit_transform(df[['color']])

/home/dazai/Yash/Data_sci/Practice /.conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [18]:
lbl_encoder.transform([['blue']])

/home/dazai/Yash/Data_sci/Practice /.conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [19]:
lbl_encoder.transform([['red']])

/home/dazai/Yash/Data_sci/Practice /.conda/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

the model might start thinking higer values corresponds to greater internal value of the variable and use that way to differntiate  or sort 
which is not correct

### Ordinal encoding 

converts categorical values into ordered integers based on a defined or natural ranking.
It assigns each category a number like 0, 1, 2, 3… depending on the order.
Useful when categories have a meaningful order (e.g., low < medium < high).
Not suitable for unordered categories because it introduces false numerical relationships.

1. HighSchool:1
2. college :2
3. Graduate:3
4. post-graduate:4

In [20]:
import pandas as pd 
from sklearn.preprocessing import OrdinalEncoder

In [23]:
df1 = pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [24]:
df1

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [27]:
#create an instance of ordinalencoder and the fit_transform

encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [29]:
encoder.fit_transform(df1[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [26]:
encoder.fit_transform([['small']])

array([[0.]])

### Target guided ordinal encoding
Target-guided ordinal encoding is a technique where categorical values are converted into ordered integers based on the target variable (y) instead of natural order.

Here’s how it works (simple):

1. For each category, compute a target statistic (usually mean of the target, e.g., probability of class 1).

2. Sort categories based on this value.

3. Assign integers (0,1,2…) according to the order.

In [31]:
import pandas as pd 

#create a simple dataframe

df2 = pd.DataFrame({
    'city':['New york','Mumbai','shanghai','beijing','london','singapore'],
    'Price':[250,167,189,494,204,320]
})

In [32]:
df2

        city  Price
0   New york    250
1     Mumbai    167
2   shanghai    189
3    beijing    494
4     london    204
5  singapore    320

In [43]:
'''we will consider price as target variable and 
try to convert city(categorical variabel )on the basis of target variable
'''
mean_price=df2.groupby('city')['Price'].mean().to_dict()

In [44]:
mean_price

{'Mumbai': 167.0,
 'New york': 250.0,
 'beijing': 494.0,
 'london': 204.0,
 'shanghai': 189.0,
 'singapore': 320.0}

In [41]:
df2['city_encoded']=df2['city'].map(mean_price)

In [46]:
df2[['Price','city_encoded']]

   Price  city_encoded
0    250         250.0
1    167         167.0
2    189         189.0
3    494         494.0
4    204         204.0
5    320         320.0

In [49]:
import seaborn as sns
df3=sns.load_dataset('tips')

In [51]:
df3

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [ ]:
sns.histplot(data=df3,x=)

In [53]:
mean_price1=df3.groupby('time')['total_bill'].mean().to_dict()

/tmp/ipykernel_82585/1780119771.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_price1=df3.groupby('time')['total_bill'].mean().to_dict()

In [56]:
mean_price1

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [54]:
df3['Time_encoded']=df3['time'].map(mean_price1)

In [57]:
df3['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64